"""
Users app for Digital Ekub Platform.

This app handles user authentication, profile management, OTP verification,
referrals, and user administration.
"""

__version__ = '1.0.0'
__app_name__ = 'users'

# Set the default app configuration
default_app_config = 'apps.users.apps.UsersConfig'

# Expose main components for easier imports
from .models import User
from .serializers import (
    UserRegistrationSerializer,
    UserLoginSerializer,
    UserProfileSerializer,
    UserProfileUpdateSerializer,
    ChangePasswordSerializer,
    OTPSendSerializer,
    OTPVerifySerializer,
    PasswordResetRequestSerializer,
    PasswordResetConfirmSerializer,
    LogoutSerializer,
    RefreshTokenSerializer,
    UserListSerializer,
    UserDetailSerializer,
    AdminUserUpdateSerializer,
    TokenObtainSerializer,
    ReferralStatsSerializer,
    EmailVerificationSerializer,
    UserBaseSerializer,
)
from .views import (
    UserRegistrationView,
    UserLoginView,
    LogoutView,
    RefreshTokenView,
    CustomTokenObtainPairView,
    MeView,
    UserProfileView,
    PublicUserProfileView,
    ChangePasswordView,
    OTPSendView,
    OTPVerifyView,
    OTPResendView,
    PasswordResetRequestView,
    PasswordResetConfirmView,
    EmailVerificationView,
    PhoneVerificationView,
    ReferralStatsView,
    ReferralListView,
    AdminUserViewSet,
    update_activity,
    DeviceRegistrationView,
)
from .permissions import (
    IsAuthenticated,
    IsVerified,
    IsPhoneVerified,
    IsEmailVerified,
    IsIdentityVerified,
    IsAdmin,
    IsSuperAdmin,
    IsActive,
    IsNotDeleted,
    IsNotSuspended,
    IsNotLocked,
    IsSameUser,
    IsSameUserOrReadOnly,
    IsSameUserOrAdmin,
    IsSameUserOrSuperAdmin,
    IsAdminOrReadOnly,
    IsSuperAdminOrReadOnly,
    IsOwnerOrReadOnly,
    IsOwnerOrAdmin,
    IsOwnerOrSuperAdmin,
    IsActiveAndVerified,
    IsVerifiedPhoneOrAdmin,
    IsVerifiedEmailOrAdmin,
    IsIdentityVerifiedOrAdmin,
    HasMinimumReputation,
    IsNotDefaulted,
    IsActiveAndPhoneVerified,
    IsActiveAndEmailVerified,
    CanCreateGroup,
    CanJoinGroup,
    CanContribute,
    IsOwnerOrReadOnlyForObject,
)
from .tasks import (
    cleanup_expired_otps,
    update_user_statistics,
    process_referral_bonus,
    unlock_locked_accounts,
    suspend_inactive_users,
    soft_delete_inactive_users,
    update_reputation_scores,
    process_defaulted_users,
    send_welcome_email,
)
from .signals import (
    user_post_save_handler,
    user_pre_save_handler,
    user_pre_delete_handler,
    user_post_delete_handler,
    user_verification_complete_handler,
    user_account_status_handler,
    user_reputation_update_handler,
    user_activity_handler,
)

__all__ = [
    # Models
    'User',
    # Serializers
    'UserRegistrationSerializer',
    'UserLoginSerializer',
    'UserProfileSerializer',
    'UserProfileUpdateSerializer',
    'ChangePasswordSerializer',
    'OTPSendSerializer',
    'OTPVerifySerializer',
    'PasswordResetRequestSerializer',
    'PasswordResetConfirmSerializer',
    'LogoutSerializer',
    'RefreshTokenSerializer',
    'UserListSerializer',
    'UserDetailSerializer',
    'AdminUserUpdateSerializer',
    'TokenObtainSerializer',
    'ReferralStatsSerializer',
    'EmailVerificationSerializer',
    'UserBaseSerializer',
    # Views
    'UserRegistrationView',
    'UserLoginView',
    'LogoutView',
    'RefreshTokenView',
    'CustomTokenObtainPairView',
    'MeView',
    'UserProfileView',
    'PublicUserProfileView',
    'ChangePasswordView',
    'OTPSendView',
    'OTPVerifyView',
    'OTPResendView',
    'PasswordResetRequestView',
    'PasswordResetConfirmView',
    'EmailVerificationView',
    'PhoneVerificationView',
    'ReferralStatsView',
    'ReferralListView',
    'AdminUserViewSet',
    'update_activity',
    'DeviceRegistrationView',
    # Permissions
    'IsAuthenticated',
    'IsVerified',
    'IsPhoneVerified',
    'IsEmailVerified',
    'IsIdentityVerified',
    'IsAdmin',
    'IsSuperAdmin',
    'IsActive',
    'IsNotDeleted',
    'IsNotSuspended',
    'IsNotLocked',
    'IsSameUser',
    'IsSameUserOrReadOnly',
    'IsSameUserOrAdmin',
    'IsSameUserOrSuperAdmin',
    'IsAdminOrReadOnly',
    'IsSuperAdminOrReadOnly',
    'IsOwnerOrReadOnly',
    'IsOwnerOrAdmin',
    'IsOwnerOrSuperAdmin',
    'IsActiveAndVerified',
    'IsVerifiedPhoneOrAdmin',
    'IsVerifiedEmailOrAdmin',
    'IsIdentityVerifiedOrAdmin',
    'HasMinimumReputation',
    'IsNotDefaulted',
    'IsActiveAndPhoneVerified',
    'IsActiveAndEmailVerified',
    'CanCreateGroup',
    'CanJoinGroup',
    'CanContribute',
    'IsOwnerOrReadOnlyForObject',
    # Tasks
    'cleanup_expired_otps',
    'update_user_statistics',
    'process_referral_bonus',
    'unlock_locked_accounts',
    'suspend_inactive_users',
    'soft_delete_inactive_users',
    'update_reputation_scores',
    'process_defaulted_users',
    'send_welcome_email',
    # Signals
    'user_post_save_handler',
    'user_pre_save_handler',
    'user_pre_delete_handler',
    'user_post_delete_handler',
    'user_verification_complete_handler',
    'user_account_status_handler',
    'user_reputation_update_handler',
    'user_activity_handler',
]

# Log app initialization
import logging
logger = logging.getLogger(__name__)
logger.info(f"Users app v{__version__} initialized")